version: "3"

services:
  autenticacao-service:
    image: guilhermejr/sistema-autenticacao-service
    container_name: autenticacao-service
    restart: always
    ports:
      - "9002:9002"

networks:
  default:
    external: true
    name: rede