spring:
  application:
    name: autenticacao-service
  profiles:
    active: prod
  config:
    import: 'vault://, configserver:http://config-server:8888'
  cloud:
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: ${VAULT_SCHEME:http}
      uri: ${VAULT_SCHEME:http}://${VAULT_HOST:localhost}:${VAULT_PORT:8200}
      token: ${VAULT_TOKEN:hvs.VSlxeCypMevB7HLAYZ1hB73L}
      generic:
        enabled: true
        application-name: autenticacao-service
    config:
#      discovery:
#        serviceId: config-server
      username: ${CONFIG_SERVER_USER:config}
      password: ${CONFIG_SERVER_PASS:o5qByEjgPOwh3yXOqf}
  boot:
    admin:
      client:
        url: ${monitoramentoHost}
        username: ${monitoramentoUser}
        password: ${monitoramentoPass}

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@